# Generated by Django 4.2.1 on 2023-06-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='number',
            new_name='product_id',
        ),
    ]
