# Generated by Django 4.2 on 2023-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_rename_image_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(upload_to="item_images"),
        ),
    ]
