# Generated by Django 4.2.1 on 2023-05-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Format',
        ),
        migrations.AlterModelOptions(
            name='format',
            options={},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='format',
        ),
    ]
