# Generated by Django 4.2.1 on 2023-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_category_format_alter_format_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('Ballada', 'Ballada'), ("Blues, Rhythm'n'Blues", "Blues, Rhythm'n'Blues"), ('Country', 'Country'), ('Dance', 'Dance'), ('Disco polo, Party, Karaoke', 'Disco polo, Party, Karaoke'), ('Dla dzieci', 'Dla dzieci'), ('Ethno, Folk, World music', 'Ethno, Folk, World music'), ('Jazz, Swing', 'Jazz, Swing'), ('Kolędy', 'Kolędy'), ('Metal', 'Metal'), ('Muzyka alternatywna', 'Muzyka alternatywna'), ('Muzyka elektroniczna', 'Muzyka elektroniczna'), ('Muzyka filmowa', 'Muzyka filmowa'), ('Muzyka klasyczna', 'Muzyka klasyczna'), ('Muzyka religijna', 'Muzyka religijna'), ('Nowe brzmienia', 'Nowe brzmienia'), ('Opera, Operetka', 'Opera, Operetka'), ('Pop', 'Pop'), ('Rap, Hip-Hop', 'Rap, Hip-Hop'), ('Reggae, Ska', 'Reggae, Ska'), ('Rock', 'Rock'), ("Rock'n'roll", "Rock'n'roll"), ('Single', 'Single'), ('Składanki', 'Składanki'), ('Soul, Funk', 'Soul, Funk'), ('Synth-pop', 'Synth-pop'), ('Pozostałe', 'Pozostałe'), ('Zestawy, pakiety', 'Zestawy, pakiety')], default='ballad', max_length=50),
        ),
    ]
