# Generated by Django 4.2.1 on 2023-06-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.format'),
        ),
    ]
